ASSUME DS:DATA, CS:CODE

DATA SEGMENT
        ARRAY DB 01H,11H,21H,61H,8H
        NUM DB 02H
        MSG1 DB "NUMBER PRESENT IN ARRAY $"
        MSG2 DB "NUMBER NOT PRESENT IN ARRAY $"
        COUNT DW 05H
DATA ENDS    
   
CODE SEGMENT
	DISP PROC NEAR
		MOV AH, 09H
		INT 21H 
		RET 
	DISP ENDP

START:  
	MOV AX, DATA         
        MOV DS, AX         
        MOV CX,COUNT
        LEA SI,ARRAY
        MOV BL,NUM

AGAIN:  
	CMP BL,[SI]
        JZ FOUND
        INC SI
	DEC CX
	JNZ AGAIN

	LEA DX,MSG2
	CALL DISP
	JMP EXIT

FOUND: 
	LEA DX,MSG1
	CALL DISP

EXIT: 
	MOV AX,4C00H
	INT 21H
	INT 03H
CODE ENDS
END START
