ASSUME CS:CODE, DS:DATA
DATA SEGMENT
ARRAY DB 01H, 81H, 91H, 71H, 41H, 61H, 21H, 51H, 31H, 11H
MINI DB 00H ; RESERVE SPACE FOR STORING THE SMALLEST VALUE
DATA ENDS
CODE SEGMENT
START:	MOV AX, DATA
	MOV DS, AX
	XOR DI, DI
	MOV AL, 255 
	MOV CL, 0AH
	LEA BX, ARRAY 
UP:	CMP AL, [BX+DI]
	JBE SKIP 
	MOV AL, [BX+DI] 
SKIP:	INC DI
	DEC CL 
	JNZ UP 
	MOV [MINI], AL
	INT 03H 
CODE ENDS
END START
